name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
    paths: ["docs~"]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

env:
  ROOT_DIR: ./docs~

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.ROOT_DIR }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: 'pnpm'
          cache-dependency-path: ${{ env.ROOT_DIR }}/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm copy-repository
          pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.ROOT_DIR }}/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
